validate

diff --git a/.github/workflows/deploy_to_azure_app_service.yml b/.github/workflows/deploy_to_azure_app_service.yml
--- a/.github/workflows/deploy_to_azure_app_service.yml
+++ b/.github/workflows/deploy_to_azure_app_service.yml
@@ -59,6 +59,17 @@ jobs:
 
           # Remove all lines starting with :: and save to final file
           grep -v "^::" terraform_output.f1 > terraform_output.json
+
+          # Validate JSON using jq
+          echo "Validating JSON..."
+          if jq . terraform_output.json > /dev/null 2>&1; then
+            echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m"
+          else
+            echo -e "\033[31mERROR: Invalid JSON generated by terraform output\033[0m"
+            echo -e "\033[34mContent of terraform_output.json:\033[0m"
+            cat terraform_output.json
+            exit 1
+          fi
           
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
@@ -107,13 +118,6 @@ jobs:
             # cat backend/terraform.config.json
           else
             echo "Error: terraform_output.json not found!"
-            cd frontend
-            echo "Frontend Folder:
-            ls -a
-            cd ..
-            cd backend
-            echo "Backend Folder:
-            ls -a
             exit 1
           fi
 
