fix 2

diff --git a/.github/workflows/deploy_to_azure_app_service.yml b/.github/workflows/deploy_to_azure_app_service.yml
--- a/.github/workflows/deploy_to_azure_app_service.yml
+++ b/.github/workflows/deploy_to_azure_app_service.yml
@@ -48,20 +48,21 @@ jobs:
 
       - name: Terraform Apply
         run: |
+          # Disable command echoing first otherwise will produce additional line in JSON making it invalid
+          set +x
+          # Run terraform
           terraform apply -auto-approve
-            # Disable command echoing first, then run the output command
-            set +x
-            terraform output -json > terraform_output.json
-            
-            # Verify JSON validity and fail if invalid
-            if ! cat terraform_output.json | python3 -m json.tool > /dev/null; then
-              echo -e "\033[31mERROR: Invalid JSON generated by terraform output\033[0m" >> $GITHUB_ENV
-              echo "Content of terraform_output.json:" >> $GITHUB_ENV
-              cat terraform_output.json
-              exit 1
-            else
-              echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m" >> $GITHUB_ENV
-            fi
+          terraform output -json > terraform_output.json
+          
+          # Verify JSON validity and fail if invalid
+          if ! cat terraform_output.json | python3 -m json.tool > /dev/null; then
+            echo -e "\033[31mERROR: Invalid JSON generated by terraform output\033[0m" >> $GITHUB_ENV
+            echo "Content of terraform_output.json:" >> $GITHUB_ENV
+            cat terraform_output.json
+            exit 1
+          else
+            echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m" >> $GITHUB_ENV
+          fi
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
         with:
