validate2

diff --git a/.github/workflows/deploy_to_azure_app_service.yml b/.github/workflows/deploy_to_azure_app_service.yml
--- a/.github/workflows/deploy_to_azure_app_service.yml
+++ b/.github/workflows/deploy_to_azure_app_service.yml
@@ -101,16 +101,39 @@ jobs:
             # For backend - can use the original format
             cp terraform_output.json backend/terraform.config.json
             
-            # cd frontend
-            # echo "Frontend Folder:
-            # ls -a
-            # cd ..
-            # cd backend
-            # echo "Backend Folder:
-            # ls -a
-            # exit 1
-            # cd ../
 
+            echo "Validating JSON Backend..."
+            if jq . backend/terraform.config.json> /dev/null 2>&1; then
+              echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m"
+            else
+              echo -e "\033[31mERROR: Invalid JSON generated by backend terraform output\033[0m"
+              echo -e "\033[34mContent of backend/terraform.config.json:\033[0m"
+              cat backend/terraform.config.json
+              exit 1
+            fi
+
+            cp terraform_output.json frontend/terraform.config.json
+
+            echo "Validating JSON Frontend..."
+            if jq . frontend/terraform.config.json> /dev/null 2>&1; then
+              echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m"
+            else
+              echo -e "\033[31mERROR: Invalid JSON generated by frontend terraform output\033[0m"
+              echo -e "\033[34mContent of frontend/terraform.config.json:\033[0m"
+              cat frontend/terraform.config.json
+              exit 1
+            fi
+
+            cd frontend
+            echo "Frontend Folder:
+            ls -a
+            cd ..
+            cd backend
+            echo "Backend Folder:
+            ls -a
+            exit 1
+            cd ../
+            
             # # Validate the JSON files
             # echo "Frontend JSON:"
             # cat frontend/terraform.config.json
