disable validation

diff --git a/.github/workflows/deploy_to_azure_app_service.yml b/.github/workflows/deploy_to_azure_app_service.yml
--- a/.github/workflows/deploy_to_azure_app_service.yml
+++ b/.github/workflows/deploy_to_azure_app_service.yml
@@ -60,14 +60,14 @@ jobs:
           sed '1d' terraform_output.raw > terraform_output.json
           
           # Verify JSON validity and fail if invalid
-          if jq -e . terraform_output.json > /dev/null 2>&1; then
-            echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m"
-          else
-            echo -e "\033[31mERROR: Invalid JSON generated by terraform output\033[0m"
-            echo -e "\033[34mContent of terraform_output.json:\033[0m"
-            cat terraform_output.json
-            exit 1
-          fi
+          # if jq -e . terraform_output.json > /dev/null 2>&1; then
+          #   echo -e "\033[32mSUCCESS: Valid JSON confirmed\033[0m"
+          # else
+          #   echo -e "\033[31mERROR: Invalid JSON generated by terraform output\033[0m"
+          #   echo -e "\033[34mContent of terraform_output.json:\033[0m"
+          #   cat terraform_output.json
+          #   exit 1
+          # fi
       - name: Upload artifact for deployment jobs
         uses: actions/upload-artifact@v4
         with:
